--- 
- name: Enable intranet services
  hosts: myhosts
  become: true
  tasks:
    - name: Ensure latest httpd and firewalld is installed
      ansible.builtin.dnf:
        name: 
           - httpd
           - firewalld
        state: present

    - name: Test html page is installed
      ansible.builtin.copy:
        content: "Welcome to the example.com intranet!\n"
        dest: /var/www/html/index.html

    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true    

    - name: Firewall permits access to httpd service
      ansible.posix.firewalld:     
        service: http
        permanent: true
        state: enabled
        immediate: true

