--- 
- name: Install and start httpd
  hosts: myhosts
  become: true
  tasks:
    - name: Ensure httpd is present
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Correct index.html is present
      ansible.builtin.copy:
        src: ../../files/index.html
        dest: /var/www/html/index.html

    - name: Ensure httpd is started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true    
